//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiCamConfig.App.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiCamConfig.App.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string ActionContinue {
            get {
                return ResourceManager.GetString("ActionContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay.
        /// </summary>
        internal static string ActionOkay {
            get {
                return ResourceManager.GetString("ActionOkay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app was created to modify settings of the 70mai dash cam. It is not an official application from the manufacturers of the hardware nor does it try to be so.
        ///
        ///Frankly, there is a reason why some of these settings are hidden from the user in the official 70mai app so proceed at your own risk. I am in no way responsible for anything that goes wrong with your dash cam.
        ///
        ///This project is open source on GitHub and licensed under Apache 2.0..
        /// </summary>
        internal static string MessageDisclaimer {
            get {
                return ResourceManager.GetString("MessageDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A connection to your dashcam could not be established. If you are connected to your dashcam you should check that the app has the required permissions and try again..
        /// </summary>
        internal static string MessageNotConnectedToDashcam {
            get {
                return ResourceManager.GetString("MessageNotConnectedToDashcam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to display..
        /// </summary>
        internal static string MessageNothingToDisplay {
            get {
                return ResourceManager.GetString("MessageNothingToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings &gt; WiFi.
        /// </summary>
        internal static string MessageWifiDirectory {
            get {
                return ResourceManager.GetString("MessageWifiDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string MessagingLoading {
            get {
                return ResourceManager.GetString("MessagingLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string TitleActions {
            get {
                return ResourceManager.GetString("TitleActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect To Dashcam.
        /// </summary>
        internal static string TitleConnectToDashcam {
            get {
                return ResourceManager.GetString("TitleConnectToDashcam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disclaimer.
        /// </summary>
        internal static string TitleDisclaimer {
            get {
                return ResourceManager.GetString("TitleDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Connected.
        /// </summary>
        internal static string TitleNotConnected {
            get {
                return ResourceManager.GetString("TitleNotConnected", resourceCulture);
            }
        }
    }
}
