//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiCamConfig.App.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiCamConfig.App.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ActionCancel {
            get {
                return ResourceManager.GetString("ActionCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string ActionContinue {
            get {
                return ResourceManager.GetString("ActionContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay.
        /// </summary>
        internal static string ActionOkay {
            get {
                return ResourceManager.GetString("ActionOkay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit request.
        /// </summary>
        internal static string ActionSubmitRequest {
            get {
                return ResourceManager.GetString("ActionSubmitRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get value.
        /// </summary>
        internal static string HintGetValue {
            get {
                return ResourceManager.GetString("HintGetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property.
        /// </summary>
        internal static string HintProperty {
            get {
                return ResourceManager.GetString("HintProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw response.
        /// </summary>
        internal static string HintRawResponse {
            get {
                return ResourceManager.GetString("HintRawResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        internal static string HintRequest {
            get {
                return ResourceManager.GetString("HintRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string HintSearch {
            get {
                return ResourceManager.GetString("HintSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set value to.
        /// </summary>
        internal static string HintSetValueTo {
            get {
                return ResourceManager.GetString("HintSetValueTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string HintSuccess {
            get {
                return ResourceManager.GetString("HintSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string HintValue {
            get {
                return ResourceManager.GetString("HintValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app was created to modify settings of the 70mai dash cam. It is not an official application from the manufacturers of the hardware nor does it try to be so.
        ///
        ///Frankly, there is a reason why some of these settings are hidden from the user in the official 70mai app so proceed at your own risk. I am in no way responsible for anything that goes wrong with your dash cam.
        ///
        ///This project is open source on GitHub and licensed under Apache 2.0..
        /// </summary>
        internal static string MessageDisclaimer {
            get {
                return ResourceManager.GetString("MessageDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication with your dash cam could not be established. Please check your connection..
        /// </summary>
        internal static string MessageNotConnectedToDashcam {
            get {
                return ResourceManager.GetString("MessageNotConnectedToDashcam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to display..
        /// </summary>
        internal static string MessageNothingToDisplay {
            get {
                return ResourceManager.GetString("MessageNothingToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred. Please try again later..
        /// </summary>
        internal static string MessageUnknownError {
            get {
                return ResourceManager.GetString("MessageUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings &gt; WiFi.
        /// </summary>
        internal static string MessageWifiDirectory {
            get {
                return ResourceManager.GetString("MessageWifiDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        internal static string MessagingConnecting {
            get {
                return ResourceManager.GetString("MessagingConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitting request....
        /// </summary>
        internal static string MessagingSubmittingRequest {
            get {
                return ResourceManager.GetString("MessagingSubmittingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string TitleActions {
            get {
                return ResourceManager.GetString("TitleActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect To Dashcam.
        /// </summary>
        internal static string TitleConnectToDashcam {
            get {
                return ResourceManager.GetString("TitleConnectToDashcam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Request.
        /// </summary>
        internal static string TitleCustomRequest {
            get {
                return ResourceManager.GetString("TitleCustomRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disclaimer.
        /// </summary>
        internal static string TitleDisclaimer {
            get {
                return ResourceManager.GetString("TitleDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Connected.
        /// </summary>
        internal static string TitleNotConnected {
            get {
                return ResourceManager.GetString("TitleNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Action.
        /// </summary>
        internal static string TitleSelectAction {
            get {
                return ResourceManager.GetString("TitleSelectAction", resourceCulture);
            }
        }
    }
}
